import { TemplateElement } from './template-elements';

// Welcome Email - Modern
export const welcomeModernElements: TemplateElement[] = [
  {
    id: 'logo-1',
    type: 'logo',
    order: 0,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Company Logo',
    width: 150,
    align: 'center',
    padding: 20,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'Welcome to Our Community!',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'image-1',
    type: 'image',
    order: 2,
    url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&h=400&fit=crop',
    alt: 'Welcome Image',
    width: 100,
    align: 'center',
    padding: 20,
    backgroundColor: 'transparent',
    borderRadius: 8,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 3,
    content: "We're thrilled to have you here! Thank you for joining our community. Get ready to discover amazing content, exclusive offers, and updates tailored just for you.",
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 20,
  },
  {
    id: 'button-1',
    type: 'button',
    order: 4,
    text: 'Get Started',
    url: 'https://example.com/get-started',
    backgroundColor: '#4A90E2',
    textColor: '#ffffff',
    align: 'center',
    padding: 20,
    borderRadius: 6,
    buttonWidth: 200,
    buttonHeight: 50,
  },
  {
    id: 'divider-1',
    type: 'divider',
    order: 5,
    color: '#e0e0e0',
    thickness: 1,
    padding: 30,
    style: 'solid',
  },
  {
    id: 'social-1',
    type: 'social',
    order: 6,
    platforms: [
      { name: 'facebook', url: 'https://facebook.com', enabled: true },
      { name: 'twitter', url: 'https://twitter.com', enabled: true },
      { name: 'instagram', url: 'https://instagram.com', enabled: true },
      { name: 'linkedin', url: 'https://linkedin.com', enabled: true },
    ],
    iconSize: 32,
    iconColor: '#4A90E2',
    align: 'center',
    padding: 20,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 7,
    companyName: 'Your Company',
    address: '123 Main Street, City, State 12345',
    links: [
      { text: 'Privacy Policy', url: 'https://example.com/privacy' },
      { text: 'Terms of Service', url: 'https://example.com/terms' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Product Launch - Bold
export const productLaunchBoldElements: TemplateElement[] = [
  {
    id: 'announcement-1',
    type: 'announcement',
    order: 0,
    text: '🎉 NEW PRODUCT LAUNCH',
    backgroundColor: '#ff6b6b',
    textColor: '#ffffff',
    fontSize: 14,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 15,
  },
  {
    id: 'logo-1',
    type: 'logo',
    order: 1,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Company Logo',
    width: 120,
    align: 'center',
    padding: 20,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 2,
    content: 'Introducing Our Latest Innovation',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 10,
  },
  {
    id: 'subheading-1',
    type: 'subheading',
    order: 3,
    content: 'The future is here',
    color: '#666666',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'italic',
    textDecoration: 'none',
    align: 'center',
    padding: 10,
  },
  {
    id: 'product-1',
    type: 'product',
    order: 4,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop',
    name: 'Premium Product',
    description: 'Experience the next generation of excellence with our latest product.',
    price: '$99.99',
    basePrice: '129.99',
    offerPrice: '99.99',
    showBasePrice: true,
    currency: 'USD',
    currencySymbol: '$',
    buttonText: 'Shop Now',
    buttonUrl: 'https://example.com/shop',
    buttonColor: '#4A90E2',
    buttonTextColor: '#ffffff',
    align: 'center',
    padding: 30,
    nameFontSize: 24,
    nameFontFamily: 'Arial, sans-serif',
    nameFontWeight: 'bold',
    nameFontStyle: 'normal',
    nameTextDecoration: 'none',
    nameColor: '#1a1a1a',
    descriptionFontSize: 16,
    descriptionFontFamily: 'Arial, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    descriptionColor: '#666666',
    priceFontSize: 28,
    priceFontFamily: 'Arial, sans-serif',
    priceFontWeight: 'bold',
    priceColor: '#4A90E2',
    buttonFontSize: 16,
    buttonFontFamily: 'Arial, sans-serif',
    buttonFontWeight: 'bold',
  },
  {
    id: 'divider-1',
    type: 'divider',
    order: 5,
    color: '#e0e0e0',
    thickness: 2,
    padding: 30,
    style: 'solid',
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 6,
    companyName: 'Your Company',
    address: '123 Main Street, City, State 12345',
    links: [
      { text: 'Shop All', url: 'https://example.com/shop' },
      { text: 'Contact Us', url: 'https://example.com/contact' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Newsletter Classic
export const newsletterClassicElements: TemplateElement[] = [
  {
    id: 'logo-1',
    type: 'logo',
    order: 0,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Newsletter Logo',
    width: 150,
    align: 'center',
    padding: 30,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'Weekly Newsletter',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Georgia, serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 10,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'January 18, 2026',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'italic',
    textDecoration: 'none',
    fontFamily: 'Georgia, serif',
    color: '#666666',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 10,
  },
  {
    id: 'divider-1',
    type: 'divider',
    order: 3,
    color: '#4A90E2',
    thickness: 2,
    padding: 20,
    style: 'solid',
  },
  {
    id: 'subheading-1',
    type: 'subheading',
    order: 4,
    content: 'This Week\'s Highlights',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Georgia, serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'left',
    padding: 20,
  },
  {
    id: 'list-1',
    type: 'list',
    order: 5,
    items: [
      'Feature Story: Latest Industry Trends',
      'Expert Insights: Tips from Professionals',
      'Community Spotlight: Member Success Stories',
      'Upcoming Events: Don\'t Miss Out',
    ],
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    padding: 20,
    align: 'left',
    bulletStyle: 'disc',
    fontSize: 16,
    fontFamily: 'Georgia, serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  {
    id: 'image-1',
    type: 'image',
    order: 6,
    url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&h=400&fit=crop',
    alt: 'Newsletter Feature Image',
    width: 100,
    align: 'center',
    padding: 20,
    backgroundColor: 'transparent',
    borderRadius: 4,
  },
  {
    id: 'text-2',
    type: 'text',
    order: 7,
    content: 'Dive into this week\'s curated content, featuring expert insights, community stories, and the latest updates from our team. We\'re committed to bringing you valuable information that matters.',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Georgia, serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'left',
    padding: 20,
  },
  {
    id: 'button-1',
    type: 'button',
    order: 8,
    text: 'Read Full Newsletter',
    url: 'https://example.com/newsletter',
    backgroundColor: '#4A90E2',
    textColor: '#ffffff',
    align: 'center',
    padding: 30,
    borderRadius: 4,
    buttonWidth: 220,
    buttonHeight: 50,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 9,
    companyName: 'Your Newsletter',
    address: '123 Newsletter Ave, City, State 12345',
    links: [
      { text: 'View Online', url: 'https://example.com/view' },
      { text: 'Archives', url: 'https://example.com/archives' },
    ],
    backgroundColor: '#f9f9f9',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Georgia, serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Flash Sale - Promotional
export const flashSaleElements: TemplateElement[] = [
  {
    id: 'announcement-1',
    type: 'announcement',
    order: 0,
    text: '⚡ FLASH SALE - 24 HOURS ONLY!',
    backgroundColor: '#ff4757',
    textColor: '#ffffff',
    fontSize: 16,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 15,
  },
  {
    id: 'coupon-1',
    type: 'coupon',
    order: 1,
    code: 'FLASH50',
    title: '50% OFF Everything!',
    description: 'Use code at checkout. Valid for 24 hours only.',
    backgroundColor: '#fff3cd',
    textColor: '#1a1a1a',
    codeBackgroundColor: '#1a1a1a',
    codeTextColor: '#ffffff',
    borderColor: '#ffc107',
    align: 'center',
    padding: 30,
    borderRadius: 8,
    titleFontSize: 24,
    titleFontFamily: 'Arial, sans-serif',
    titleFontWeight: 'bold',
    titleFontStyle: 'normal',
    titleTextDecoration: 'none',
    descriptionFontSize: 14,
    descriptionFontFamily: 'Arial, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    codeFontSize: 32,
    codeFontFamily: 'Courier New, monospace',
    codeFontWeight: 'bold',
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 2,
    content: 'Unbeatable Deals Await',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'twocolumn-1',
    type: 'twocolumn',
    order: 3,
    leftContent: {
      type: 'image',
      url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop',
      alt: 'Product 1',
      width: 100,
    },
    rightContent: {
      type: 'text',
      content: 'Premium Headphones\n\nWas: $199\nNow: $99',
      fontSize: 16,
      fontFamily: 'Arial, sans-serif',
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#1a1a1a',
    },
    padding: 20,
    columnGap: 20,
    backgroundColor: 'transparent',
  },
  {
    id: 'button-1',
    type: 'button',
    order: 4,
    text: 'Shop Now',
    url: 'https://example.com/sale',
    backgroundColor: '#ff4757',
    textColor: '#ffffff',
    align: 'center',
    padding: 30,
    borderRadius: 6,
    buttonWidth: 200,
    buttonHeight: 50,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 5,
    content: '⏰ Hurry! Sale ends in 24 hours',
    fontSize: 14,
    fontWeight: 'bold',
    fontStyle: 'italic',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#ff4757',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 20,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 6,
    companyName: 'Your Store',
    address: '123 Shopping Street, City, State 12345',
    links: [
      { text: 'Shop All', url: 'https://example.com/shop' },
      { text: 'Customer Service', url: 'https://example.com/support' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Order Confirmation - Transactional
export const orderConfirmationElements: TemplateElement[] = [
  {
    id: 'logo-1',
    type: 'logo',
    order: 0,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Company Logo',
    width: 140,
    align: 'center',
    padding: 30,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'Order Confirmed!',
    level: 'h1',
    color: '#27ae60',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'Thank you for your order! We\'ll send you a shipping confirmation email as soon as your order ships.',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 20,
  },
  {
    id: 'table-1',
    type: 'table',
    order: 3,
    headers: ['Item', 'Quantity', 'Price'],
    rows: [
      ['Premium Product', '1', '$99.99'],
      ['Standard Shipping', '1', '$9.99'],
    ],
    tableWidth: 100,
    cellPadding: 15,
    headerBackgroundColor: '#4A90E2',
    headerTextColor: '#ffffff',
    rowBackgroundColor: '#ffffff',
    rowTextColor: '#1a1a1a',
    borderColor: '#e0e0e0',
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Arial, sans-serif',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-2',
    type: 'text',
    order: 4,
    content: 'Order Total: $109.98',
    fontSize: 20,
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#1a1a1a',
    backgroundColor: '#f9f9f9',
    align: 'right',
    padding: 20,
  },
  {
    id: 'button-1',
    type: 'button',
    order: 5,
    text: 'Track Order',
    url: 'https://example.com/track',
    backgroundColor: '#4A90E2',
    textColor: '#ffffff',
    align: 'center',
    padding: 30,
    borderRadius: 6,
    buttonWidth: 200,
    buttonHeight: 50,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 6,
    companyName: 'Your Store',
    address: '123 Commerce Street, City, State 12345',
    links: [
      { text: 'Order Status', url: 'https://example.com/orders' },
      { text: 'Support', url: 'https://example.com/support' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: false,
  },
];

// Event Invitation
export const eventInvitationElements: TemplateElement[] = [
  {
    id: 'image-1',
    type: 'image',
    order: 0,
    url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&h=300&fit=crop',
    alt: 'Event Banner',
    width: 100,
    align: 'center',
    padding: 0,
    backgroundColor: 'transparent',
    borderRadius: 0,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'You\'re Invited!',
    level: 'h1',
    color: '#8e44ad',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 30,
  },
  {
    id: 'subheading-1',
    type: 'subheading',
    order: 2,
    content: 'Annual Company Gala',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 10,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 3,
    content: '📅 Date: February 15, 2026\n⏰ Time: 7:00 PM - 11:00 PM\n📍 Location: Grand Ballroom, City Center',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: '#f9f9f9',
    align: 'left',
    padding: 30,
  },
  {
    id: 'cta-1',
    type: 'cta',
    order: 4,
    title: 'Join Us for an Unforgettable Evening',
    description: 'Network with industry leaders, enjoy fine dining, and celebrate our achievements together.',
    buttonText: 'RSVP Now',
    buttonUrl: 'https://example.com/rsvp',
    backgroundColor: '#f9f3ff',
    textColor: '#1a1a1a',
    buttonColor: '#8e44ad',
    buttonTextColor: '#ffffff',
    padding: 30,
    align: 'center',
    titleFontSize: 24,
    titleFontFamily: 'Arial, sans-serif',
    titleFontWeight: 'bold',
    titleFontStyle: 'normal',
    titleTextDecoration: 'none',
    descriptionFontSize: 16,
    descriptionFontFamily: 'Arial, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    buttonFontSize: 16,
    buttonFontFamily: 'Arial, sans-serif',
    buttonFontWeight: 'bold',
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 5,
    companyName: 'Your Company',
    address: '123 Event Plaza, City, State 12345',
    links: [
      { text: 'Event Details', url: 'https://example.com/event' },
      { text: 'Contact Us', url: 'https://example.com/contact' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Password Reset - Transactional
export const passwordResetElements: TemplateElement[] = [
  {
    id: 'logo-1',
    type: 'logo',
    order: 0,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Company Logo',
    width: 140,
    align: 'center',
    padding: 30,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'Password Reset Request',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'We received a request to reset your password. Click the button below to create a new password.',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 20,
  },
  {
    id: 'button-1',
    type: 'button',
    order: 3,
    text: 'Reset Password',
    url: 'https://example.com/reset',
    backgroundColor: '#e74c3c',
    textColor: '#ffffff',
    align: 'center',
    padding: 30,
    borderRadius: 6,
    buttonWidth: 200,
    buttonHeight: 50,
  },
  {
    id: 'text-2',
    type: 'text',
    order: 4,
    content: 'If you didn\'t request a password reset, please ignore this email or contact support if you have concerns.',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'italic',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#999999',
    backgroundColor: '#fff8f8',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-3',
    type: 'text',
    order: 5,
    content: 'This link will expire in 24 hours.',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#666666',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 10,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 6,
    companyName: 'Your Company',
    address: '123 Security Street, City, State 12345',
    links: [
      { text: 'Support', url: 'https://example.com/support' },
      { text: 'Security', url: 'https://example.com/security' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: false,
  },
];

// Promotional Minimal
export const promotionalMinimalElements: TemplateElement[] = [
  {
    id: 'spacer-1',
    type: 'spacer',
    order: 0,
    height: 40,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'Limited Time Offer',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Helvetica, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'Exclusive savings just for you',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'italic',
    textDecoration: 'none',
    fontFamily: 'Helvetica, sans-serif',
    color: '#666666',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 10,
  },
  {
    id: 'spacer-2',
    type: 'spacer',
    order: 3,
    height: 30,
  },
  {
    id: 'image-1',
    type: 'image',
    order: 4,
    url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=500&h=500&fit=crop',
    alt: 'Product Image',
    width: 80,
    align: 'center',
    padding: 20,
    backgroundColor: 'transparent',
    borderRadius: 8,
  },
  {
    id: 'pricing-1',
    type: 'pricing',
    order: 5,
    name: 'Premium Plan',
    description: 'Everything you need to succeed',
    currency: 'USD',
    currencySymbol: '$',
    originalPrice: '49.99',
    offerPrice: '29.99',
    features: [
      'Unlimited access',
      'Priority support',
      'Advanced features',
      'No commitments',
    ],
    buttonText: 'Get Started',
    buttonUrl: 'https://example.com/pricing',
    backgroundColor: '#f9f9f9',
    textColor: '#1a1a1a',
    buttonColor: '#4A90E2',
    buttonTextColor: '#ffffff',
    align: 'center',
    padding: 30,
    showOriginalPrice: true,
    nameFontSize: 24,
    nameFontFamily: 'Helvetica, sans-serif',
    nameFontWeight: 'bold',
    nameFontStyle: 'normal',
    nameTextDecoration: 'none',
    descriptionFontSize: 16,
    descriptionFontFamily: 'Helvetica, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    featuresFontSize: 14,
    featuresFontFamily: 'Helvetica, sans-serif',
    featuresFontWeight: 'normal',
    featuresFontStyle: 'normal',
    featuresTextDecoration: 'none',
  },
  {
    id: 'spacer-3',
    type: 'spacer',
    order: 6,
    height: 40,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 7,
    companyName: 'Your Brand',
    address: '123 Minimal Street, City, State 12345',
    links: [
      { text: 'Privacy', url: 'https://example.com/privacy' },
      { text: 'Terms', url: 'https://example.com/terms' },
    ],
    backgroundColor: 'transparent',
    textColor: '#999999',
    fontSize: 11,
    fontFamily: 'Helvetica, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 20,
    showUnsubscribe: true,
  },
];

// Welcome Elegant
export const welcomeElegantElements: TemplateElement[] = [
  {
    id: 'logo-1',
    type: 'logo',
    order: 0,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Elegant Logo',
    width: 160,
    align: 'center',
    padding: 40,
  },
  {
    id: 'greeting-1',
    type: 'greeting',
    order: 1,
    template: 'Dear {{first_name}},',
    fallback: 'Dear Valued Customer,',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontFamily: 'Georgia, serif',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    align: 'left',
    padding: 30,
    availableFields: ['first_name', 'last_name', 'full_name', 'email', 'company'],
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'It is with great pleasure that we welcome you to our distinguished community. Your decision to join us marks the beginning of an exceptional journey.',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Georgia, serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'left',
    padding: 20,
  },
  {
    id: 'quote-1',
    type: 'quote',
    order: 3,
    text: 'Excellence is not a destination; it is a continuous journey that never ends.',
    author: 'Brian Tracy',
    fontSize: 18,
    fontFamily: 'Georgia, serif',
    fontWeight: 'normal',
    fontStyle: 'italic',
    textDecoration: 'none',
    color: '#555555',
    backgroundColor: '#f9f9f9',
    borderColor: '#4A90E2',
    borderWidth: 3,
    padding: 30,
    align: 'center',
  },
  {
    id: 'signature-1',
    type: 'signature',
    order: 4,
    name: 'Jane Doe',
    title: 'Chief Executive Officer',
    company: 'Your Company',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    imageAlign: 'left',
    fontSize: 14,
    fontFamily: 'Georgia, serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    textColor: '#1a1a1a',
    backgroundColor: 'transparent',
    padding: 30,
  },
  {
    id: 'divider-1',
    type: 'divider',
    order: 5,
    color: '#d4af37',
    thickness: 2,
    padding: 30,
    style: 'solid',
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 6,
    companyName: 'Your Company',
    address: '123 Elegant Boulevard, City, State 12345',
    links: [
      { text: 'About Us', url: 'https://example.com/about' },
      { text: 'Contact', url: 'https://example.com/contact' },
    ],
    backgroundColor: '#f9f9f9',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Georgia, serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Monthly Roundup
export const monthlyRoundupElements: TemplateElement[] = [
  {
    id: 'announcement-1',
    type: 'announcement',
    order: 0,
    text: '📰 MONTHLY ROUNDUP',
    backgroundColor: '#4A90E2',
    textColor: '#ffffff',
    fontSize: 14,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 15,
  },
  {
    id: 'logo-1',
    type: 'logo',
    order: 1,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Newsletter Logo',
    width: 150,
    align: 'center',
    padding: 30,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 2,
    content: 'January 2026 Highlights',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'navigation-1',
    type: 'navigation',
    order: 3,
    links: [
      { text: 'Features', url: '#features' },
      { text: 'Updates', url: '#updates' },
      { text: 'Community', url: '#community' },
      { text: 'Events', url: '#events' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#4A90E2',
    fontSize: 14,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'subheading-1',
    type: 'subheading',
    order: 4,
    content: 'Top Stories This Month',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'left',
    padding: 30,
  },
  {
    id: 'twocolumn-1',
    type: 'twocolumn',
    order: 5,
    leftContent: {
      type: 'image',
      url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=300&h=200&fit=crop',
      alt: 'Story 1',
      width: 100,
    },
    rightContent: {
      type: 'text',
      content: 'New Product Features\n\nDiscover the latest updates and improvements we\'ve made this month.',
      fontSize: 14,
      fontFamily: 'Arial, sans-serif',
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#4a4a4a',
    },
    padding: 20,
    columnGap: 20,
    backgroundColor: 'transparent',
  },
  {
    id: 'button-1',
    type: 'button',
    order: 6,
    text: 'Read Full Newsletter',
    url: 'https://example.com/newsletter',
    backgroundColor: '#4A90E2',
    textColor: '#ffffff',
    align: 'center',
    padding: 30,
    borderRadius: 6,
    buttonWidth: 220,
    buttonHeight: 50,
  },
  {
    id: 'social-1',
    type: 'social',
    order: 7,
    platforms: [
      { name: 'facebook', url: 'https://facebook.com', enabled: true },
      { name: 'twitter', url: 'https://twitter.com', enabled: true },
      { name: 'linkedin', url: 'https://linkedin.com', enabled: true },
    ],
    iconSize: 32,
    iconColor: '#4A90E2',
    align: 'center',
    padding: 30,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 8,
    companyName: 'Your Newsletter',
    address: '123 Newsletter Street, City, State 12345',
    links: [
      { text: 'Archive', url: 'https://example.com/archive' },
      { text: 'Preferences', url: 'https://example.com/preferences' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Seasonal Promotional
export const seasonalPromotionalElements: TemplateElement[] = [
  {
    id: 'image-1',
    type: 'image',
    order: 0,
    url: 'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?w=600&h=300&fit=crop',
    alt: 'Seasonal Banner',
    width: 100,
    align: 'center',
    padding: 0,
    backgroundColor: 'transparent',
    borderRadius: 0,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'New Season, New Collection',
    level: 'h1',
    color: '#2c3e50',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 30,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'Discover the latest trends and must-have items for the season. Shop now and elevate your style.',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 20,
  },
  {
    id: 'twocolumn-1',
    type: 'twocolumn',
    order: 3,
    leftContent: {
      type: 'image',
      url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300&h=400&fit=crop',
      alt: 'Product 1',
      width: 100,
    },
    rightContent: {
      type: 'image',
      url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=300&h=400&fit=crop',
      alt: 'Product 2',
      width: 100,
    },
    padding: 20,
    columnGap: 20,
    backgroundColor: 'transparent',
  },
  {
    id: 'cta-1',
    type: 'cta',
    order: 4,
    title: 'Limited Time: 30% Off',
    description: 'Use code SEASON30 at checkout. Offer valid through end of month.',
    buttonText: 'Shop Collection',
    buttonUrl: 'https://example.com/collection',
    backgroundColor: '#ecf0f1',
    textColor: '#2c3e50',
    buttonColor: '#e74c3c',
    buttonTextColor: '#ffffff',
    padding: 30,
    align: 'center',
    titleFontSize: 28,
    titleFontFamily: 'Arial, sans-serif',
    titleFontWeight: 'bold',
    titleFontStyle: 'normal',
    titleTextDecoration: 'none',
    descriptionFontSize: 16,
    descriptionFontFamily: 'Arial, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    buttonFontSize: 16,
    buttonFontFamily: 'Arial, sans-serif',
    buttonFontWeight: 'bold',
  },
  {
    id: 'social-1',
    type: 'social',
    order: 5,
    platforms: [
      { name: 'facebook', url: 'https://facebook.com', enabled: true },
      { name: 'instagram', url: 'https://instagram.com', enabled: true },
      { name: 'twitter', url: 'https://twitter.com', enabled: true },
    ],
    iconSize: 32,
    iconColor: '#2c3e50',
    align: 'center',
    padding: 30,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 6,
    companyName: 'Your Fashion Brand',
    address: '123 Style Avenue, City, State 12345',
    links: [
      { text: 'Shop', url: 'https://example.com/shop' },
      { text: 'Lookbook', url: 'https://example.com/lookbook' },
    ],
    backgroundColor: '#2c3e50',
    textColor: '#ecf0f1',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Customer Thank You
export const customerThankYouElements: TemplateElement[] = [
  {
    id: 'logo-1',
    type: 'logo',
    order: 0,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Company Logo',
    width: 140,
    align: 'center',
    padding: 30,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 1,
    content: 'Thank You! 💙',
    level: 'h1',
    color: '#4A90E2',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 2,
    content: 'We truly appreciate your business and support. Your trust in us means everything.',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 20,
  },
  {
    id: 'image-1',
    type: 'image',
    order: 3,
    url: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=500&h=300&fit=crop',
    alt: 'Thank You',
    width: 80,
    align: 'center',
    padding: 30,
    backgroundColor: 'transparent',
    borderRadius: 12,
  },
  {
    id: 'subheading-1',
    type: 'subheading',
    order: 4,
    content: 'As a token of our appreciation...',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'coupon-1',
    type: 'coupon',
    order: 5,
    code: 'THANKYOU15',
    title: '15% Off Your Next Purchase',
    description: 'Valid for 30 days on your next order',
    backgroundColor: '#e8f4fd',
    textColor: '#1a1a1a',
    codeBackgroundColor: '#4A90E2',
    codeTextColor: '#ffffff',
    borderColor: '#4A90E2',
    align: 'center',
    padding: 30,
    borderRadius: 10,
    titleFontSize: 22,
    titleFontFamily: 'Arial, sans-serif',
    titleFontWeight: 'bold',
    titleFontStyle: 'normal',
    titleTextDecoration: 'none',
    descriptionFontSize: 14,
    descriptionFontFamily: 'Arial, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    codeFontSize: 28,
    codeFontFamily: 'Courier New, monospace',
    codeFontWeight: 'bold',
  },
  {
    id: 'button-1',
    type: 'button',
    order: 6,
    text: 'Start Shopping',
    url: 'https://example.com/shop',
    backgroundColor: '#4A90E2',
    textColor: '#ffffff',
    align: 'center',
    padding: 30,
    borderRadius: 6,
    buttonWidth: 200,
    buttonHeight: 50,
  },
  {
    id: 'divider-1',
    type: 'divider',
    order: 7,
    color: '#e0e0e0',
    thickness: 1,
    padding: 30,
    style: 'solid',
  },
  {
    id: 'text-2',
    type: 'text',
    order: 8,
    content: 'Have questions? Our support team is here to help!',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#666666',
    backgroundColor: 'transparent',
    align: 'center',
    padding: 10,
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 9,
    companyName: 'Your Company',
    address: '123 Gratitude Lane, City, State 12345',
    links: [
      { text: 'Support', url: 'https://example.com/support' },
      { text: 'FAQ', url: 'https://example.com/faq' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Announcement Update
export const announcementUpdateElements: TemplateElement[] = [
  {
    id: 'announcement-1',
    type: 'announcement',
    order: 0,
    text: '📢 IMPORTANT UPDATE',
    backgroundColor: '#f39c12',
    textColor: '#ffffff',
    fontSize: 16,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 15,
  },
  {
    id: 'logo-1',
    type: 'logo',
    order: 1,
    url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=80&fit=crop',
    alt: 'Company Logo',
    width: 140,
    align: 'center',
    padding: 30,
  },
  {
    id: 'heading-1',
    type: 'heading',
    order: 2,
    content: 'System Upgrade Notice',
    level: 'h1',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'center',
    padding: 20,
  },
  {
    id: 'text-1',
    type: 'text',
    order: 3,
    content: 'We\'re excited to announce a major system upgrade scheduled for this weekend. This improvement will bring you enhanced features, better performance, and an improved user experience.',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    fontFamily: 'Arial, sans-serif',
    color: '#4a4a4a',
    backgroundColor: 'transparent',
    align: 'left',
    padding: 20,
  },
  {
    id: 'subheading-1',
    type: 'subheading',
    order: 4,
    content: 'What You Need to Know:',
    color: '#1a1a1a',
    backgroundColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    fontStyle: 'normal',
    textDecoration: 'none',
    align: 'left',
    padding: 20,
  },
  {
    id: 'list-1',
    type: 'list',
    order: 5,
    items: [
      'Scheduled Maintenance: Saturday, 2:00 AM - 6:00 AM EST',
      'Expected Downtime: Approximately 4 hours',
      'New Features: Enhanced dashboard, faster loading times',
      'Action Required: Please save any work before maintenance begins',
    ],
    color: '#4a4a4a',
    backgroundColor: '#f9f9f9',
    padding: 25,
    align: 'left',
    bulletStyle: 'disc',
    fontSize: 15,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  {
    id: 'cta-1',
    type: 'cta',
    order: 6,
    title: 'Questions About the Upgrade?',
    description: 'Our support team is ready to assist you with any concerns.',
    buttonText: 'Contact Support',
    buttonUrl: 'https://example.com/support',
    backgroundColor: '#fff3cd',
    textColor: '#1a1a1a',
    buttonColor: '#f39c12',
    buttonTextColor: '#ffffff',
    padding: 30,
    align: 'center',
    titleFontSize: 20,
    titleFontFamily: 'Arial, sans-serif',
    titleFontWeight: 'bold',
    titleFontStyle: 'normal',
    titleTextDecoration: 'none',
    descriptionFontSize: 14,
    descriptionFontFamily: 'Arial, sans-serif',
    descriptionFontWeight: 'normal',
    descriptionFontStyle: 'normal',
    descriptionTextDecoration: 'none',
    buttonFontSize: 16,
    buttonFontFamily: 'Arial, sans-serif',
    buttonFontWeight: 'bold',
  },
  {
    id: 'footer-1',
    type: 'footer',
    order: 7,
    companyName: 'Your Company',
    address: '123 Update Street, City, State 12345',
    links: [
      { text: 'Status Page', url: 'https://example.com/status' },
      { text: 'Support', url: 'https://example.com/support' },
    ],
    backgroundColor: '#f5f5f5',
    textColor: '#666666',
    fontSize: 12,
    fontFamily: 'Arial, sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    padding: 30,
    showUnsubscribe: true,
  },
];

// Map template IDs to their element structures
export const predefinedTemplateStructures: { [key: string]: TemplateElement[] } = {
  'template-welcome-modern': welcomeModernElements,
  'template-product-launch-bold': productLaunchBoldElements,
  'template-newsletter-classic': newsletterClassicElements,
  'template-flash-sale': flashSaleElements,
  'template-order-confirmation': orderConfirmationElements,
  'template-event-invitation': eventInvitationElements,
  'template-password-reset': passwordResetElements,
  'template-promotional-minimal': promotionalMinimalElements,
  'template-welcome-elegant': welcomeElegantElements,
  'template-monthly-roundup': monthlyRoundupElements,
  'template-seasonal-promotional': seasonalPromotionalElements,
  'template-customer-thankyou': customerThankYouElements,
  'template-announcement-update': announcementUpdateElements,
};
